### ISSUE TITLE
Pressing ENTER doesn't update PowerLevel10k status

### ISSUE THREAD

**Issue by farzadmf** [desyncr/auto-ls#12]
Hi,

First of all, thank you for your cool utility; I'm really enjoying it

There's just one issue for me: I'm using PowerLevel10k for my prompt, and normally, in my command line, I'm used to press ENTER to make sure my prompt is up-to-date (example: git prompt), but I *think* (I'm not sure) this plugin is preventing that because when I press ENTER, I still see my non-updated prompt, and I need to run a random command (e.g., an empty `echo`) so that my prompt gets updated

Any thoughts on this?

**Comment by desyncr** [comment]
I do not use that prompt but I'll take a look at that to see if I can reproduce the behavior you mention.

**Comment by desyncr** [comment]
Can confirm this is happening. How to reproduce:

Requirements:
- Install and activate P10k theme
- Configure prompt with a clock: hh:mm:ss
- Install auto-ls

Steps to reproduce:
- On any prompt press Enter key multiple times

Expected behaviour:
- Clock should show seconds passing

Actual behaviour:
- Clock's seconds don't update

**Comment by desyncr** [comment]
Should be fixed on https://github.com/desyncr/auto-ls/commit/12145157807485eeb3e02ea7fbff2c719e86ca12
